// <auto-generated />
namespace SecondHandMarket.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class adfs1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adfs1));
        
        string IMigrationMetadata.Id
        {
            get { return "201304161450180_adfs1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
