// <auto-generated />
namespace SecondHandMarket.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class adfs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adfs));
        
        string IMigrationMetadata.Id
        {
            get { return "201304161436389_adfs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
