// <auto-generated />
namespace SecondHandMarket.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ddddd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ddddd));
        
        string IMigrationMetadata.Id
        {
            get { return "201304171510131_ddddd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
